# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e7666a6d00677b96e825119d3095fb0e9bec9089b02be8442f0b0abe9e28cac4b87c0f460156964b1cfe8f42f23f46804df726dec529d9d7f30561196a2be10

test:
  secret_key_base: 24f9975eee1d6c5060e6331fda5213987ccec588ffc364018427ca2cdb509f49551036b336a2504e8b4557afb745309d5e4288b8eaa190f58af3792bf3938285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
